services:
  - type: web
    name: telegram-osint-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8415869688:AAHSiFfKuAo4_75e_835hgebl2iKku3RJKg
      - key: MONGO_URI
        value: mongodb+srv://osXspace:osXspace@cluster0.k3k6yzj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: ADMIN_IDS
        value: "7167145056,6435989814"
